-- Create a table for detailed analytics events
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    path TEXT NOT NULL,
    referrer TEXT,
    user_agent TEXT,
    device_type TEXT, -- 'mobile', 'desktop', 'tablet', 'bot'
    country TEXT,     -- ISO code if available (optional for now)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts
CREATE POLICY "Allow anonymous analytics logging" 
ON public.analytics_events 
FOR INSERT 
WITH CHECK (true);

-- Allow admins to read all events
CREATE POLICY "Allow admins to read analytics" 
ON public.analytics_events 
FOR SELECT 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Enhanced RPC function to track view with extra data
CREATE OR REPLACE FUNCTION public.track_page_view(
    p_session_id UUID,
    p_path TEXT,
    p_referrer TEXT DEFAULT NULL,
    p_user_agent TEXT DEFAULT NULL,
    p_device_type TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- 1. Insert into detailed events log
    INSERT INTO public.analytics_events (session_id, path, referrer, user_agent, device_type)
    VALUES (p_session_id, p_path, p_referrer, p_user_agent, p_device_type);

    -- 2. Update active sessions (Heartbeat)
    INSERT INTO public.active_sessions (session_id, user_agent, current_path, last_seen)
    VALUES (p_session_id, p_user_agent, p_path, now())
    ON CONFLICT (session_id) 
    DO UPDATE SET 
        current_path = EXCLUDED.current_path,
        last_seen = EXCLUDED.last_seen;

    -- 3. Increment article view count (if path is an article)
    -- Extract slug from path: /guides/category/slug
    -- This is a bit complex in SQL regex, so we'll stick to the previous simple increment if we can ID the article.
    -- For now, we rely on the client or API to call increment_article_view separately if needed, 
    -- OR we just rely on this event log for "Top Articles" calculation.
    
    -- We can try to match the path to an article to increment views
    -- regex pattern: ^/guides/[^/]+/([^/]+)$
    
    -- (Optional: Optimized increment logic could go here)
END;
$$;

-- Function to get traffic sources
CREATE OR REPLACE FUNCTION public.get_traffic_sources(days_ago INT DEFAULT 30)
RETURNS TABLE (source TEXT, count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COALESCE(NULLIF(regexp_replace(referrer, '^https?://([^/]+).*', '\1'), ''), 'Direct / Unknown') AS source,
        COUNT(*) as count
    FROM public.analytics_events
    WHERE created_at > now() - (days_ago || ' days')::interval
    GROUP BY source
    ORDER BY count DESC
    LIMIT 10;
END;
$$;

-- Function to get device usage
CREATE OR REPLACE FUNCTION public.get_device_usage(days_ago INT DEFAULT 30)
RETURNS TABLE (device TEXT, count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COALESCE(device_type, 'desktop') AS device,
        COUNT(*) as count
    FROM public.analytics_events
    WHERE created_at > now() - (days_ago || ' days')::interval
    GROUP BY device
    ORDER BY count DESC;
END;
$$;
