-- DROP table first to ensure clean state (WARNING: Deletes existing comments)
DROP TABLE IF EXISTS public.comments CASCADE;

-- Create comments table
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL, -- Kept private, not displayed
    content TEXT NOT NULL,
    is_approved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    ip_address TEXT -- For spam blocking if needed
);

-- Add comments_locked flag to articles
ALTER TABLE public.articles 
ADD COLUMN IF NOT EXISTS comments_locked BOOLEAN DEFAULT FALSE;

-- Enable RLS
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can insert (post comment)
CREATE POLICY "Allow public insert comments" 
ON public.comments 
FOR INSERT 
WITH CHECK (true);

-- Policy: Public can view APPROVED comments
CREATE POLICY "Allow public view approved comments" 
ON public.comments 
FOR SELECT 
USING (is_approved = true);

-- Policy: Admins can do everything
CREATE POLICY "Allow admins full access to comments" 
ON public.comments 
FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);
