-- Ensure Comments Table Exists
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    content TEXT NOT NULL,
    is_approved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    ip_address TEXT,
    parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Ensure Columns Exist (in case table existed but columns missing)
DO $$
BEGIN
    -- Add parent_id if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'comments' AND column_name = 'parent_id') THEN
        ALTER TABLE public.comments ADD COLUMN parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE;
    END IF;

    -- Add user_id if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'comments' AND column_name = 'user_id') THEN
        ALTER TABLE public.comments ADD COLUMN user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
    END IF;

    -- Add comments_locked to articles if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'comments_locked') THEN
        ALTER TABLE public.articles ADD COLUMN comments_locked BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- Fix User ID Constraint (If it references auth.users instead of profiles)
-- We try to drop any existing FK on user_id and re-add it to profiles
DO $$
BEGIN
    ALTER TABLE public.comments DROP CONSTRAINT IF EXISTS comments_user_id_fkey;
    ALTER TABLE public.comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore if constraint doesn't exist or fails (likely correct already)
END $$;

-- Enable RLS
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Re-apply Policies
DROP POLICY IF EXISTS "Allow public insert comments" ON public.comments;
CREATE POLICY "Allow public insert comments" ON public.comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public view approved comments" ON public.comments;
CREATE POLICY "Allow public view approved comments" ON public.comments FOR SELECT USING (is_approved = true);

DROP POLICY IF EXISTS "Allow admins full access to comments" ON public.comments;
CREATE POLICY "Allow admins full access to comments" ON public.comments FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

DROP POLICY IF EXISTS "Allow users to delete own comments" ON public.comments;
CREATE POLICY "Allow users to delete own comments" ON public.comments FOR DELETE USING (auth.uid() = user_id);
