-- Create a table to track individual views with timestamps
CREATE TABLE IF NOT EXISTS public.article_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT REFERENCES public.articles(id) ON DELETE CASCADE,
    viewed_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.article_views ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (views can happen without login)
CREATE POLICY "Allow anonymous view logging" 
ON public.article_views 
FOR INSERT 
WITH CHECK (true);

-- Function to increment view and log it
CREATE OR REPLACE FUNCTION public.increment_article_view(target_article_id BIGINT)
RETURNS void AS $$
BEGIN
    -- Log the individual view
    INSERT INTO public.article_views (article_id) VALUES (target_article_id);
    
    -- Increment the global counter for legacy/fast lookups
    UPDATE public.articles 
    SET views_count = views_count + 1 
    WHERE id = target_article_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
